/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.AetherVoyages.view;

import br.com.AetherVoyages.dao.InterPassengerDAO;
import br.com.AetherVoyages.model.InterPassenger;

/**
 *
 * @author wslav
 */
public class International extends javax.swing.JFrame {

    /**
     * Creates new form International
     */
    public International() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpButtons = new javax.swing.JPanel();
        bntUpdateInter = new javax.swing.JButton();
        bntNewInter = new javax.swing.JButton();
        bntDeleteInter = new javax.swing.JButton();
        bntSaveInter = new javax.swing.JButton();
        bntMain = new javax.swing.JButton();
        txtNameInter = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmailInter = new javax.swing.JTextField();
        lblCPFInter = new javax.swing.JLabel();
        txtCPFInter = new javax.swing.JFormattedTextField();
        lblRGInter = new javax.swing.JLabel();
        txtRGInter = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblAirlineTick = new javax.swing.JLabel();
        jRBRoundTrip = new javax.swing.JRadioButton();
        jRBDerpature = new javax.swing.JRadioButton();
        lblBoarding = new javax.swing.JLabel();
        txtBoardingInter = new javax.swing.JTextField();
        lblDestinyInter = new javax.swing.JLabel();
        txtDestinyInter = new javax.swing.JTextField();
        lblDestinyInter1 = new javax.swing.JLabel();
        txtDestinyInter1 = new javax.swing.JTextField();
        jCBPassportCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jpButtons.setBackground(new java.awt.Color(0, 102, 102));
        jpButtons.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bntUpdateInter.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bntUpdateInter.setForeground(new java.awt.Color(0, 0, 0));
        bntUpdateInter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/AetherVoyages/img/businessapplication_edit_male_user_thepencil_theclient_negocio_2321.png"))); // NOI18N
        bntUpdateInter.setText("Update");
        bntUpdateInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntUpdateInterActionPerformed(evt);
            }
        });

        bntNewInter.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bntNewInter.setForeground(new java.awt.Color(0, 0, 0));
        bntNewInter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/AetherVoyages/img/business_application_addmale_useradd_insert_add_user_client_2312 (1).png"))); // NOI18N
        bntNewInter.setText("New");

        bntDeleteInter.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bntDeleteInter.setForeground(new java.awt.Color(0, 0, 0));
        bntDeleteInter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/AetherVoyages/img/delete_delete_deleteusers_delete_male_user_maleclient_2348.png"))); // NOI18N
        bntDeleteInter.setText("Delete");
        bntDeleteInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDeleteInterActionPerformed(evt);
            }
        });

        bntSaveInter.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bntSaveInter.setForeground(new java.awt.Color(0, 0, 0));
        bntSaveInter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/AetherVoyages/img/Save_37110.png"))); // NOI18N
        bntSaveInter.setText("Save");
        bntSaveInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSaveInterActionPerformed(evt);
            }
        });

        bntMain.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bntMain.setForeground(new java.awt.Color(0, 0, 0));
        bntMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/AetherVoyages/img/Login_37128.png"))); // NOI18N
        bntMain.setText("Main");
        bntMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpButtonsLayout = new javax.swing.GroupLayout(jpButtons);
        jpButtons.setLayout(jpButtonsLayout);
        jpButtonsLayout.setHorizontalGroup(
            jpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpButtonsLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(bntUpdateInter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntDeleteInter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntNewInter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntSaveInter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntMain)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jpButtonsLayout.setVerticalGroup(
            jpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpButtonsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntUpdateInter)
                    .addComponent(bntNewInter)
                    .addComponent(bntDeleteInter)
                    .addComponent(bntSaveInter)
                    .addComponent(bntMain, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        txtNameInter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNameInter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNameInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameInterActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 0));
        lblName.setText("Name:");

        lblID.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(0, 0, 0));
        lblID.setText("ID:");

        txtID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail.setText("E-mail:");

        txtEmailInter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmailInter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEmailInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailInterActionPerformed(evt);
            }
        });

        lblCPFInter.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblCPFInter.setForeground(new java.awt.Color(0, 0, 0));
        lblCPFInter.setText("CPF:");

        txtCPFInter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            txtCPFInter.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblRGInter.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblRGInter.setForeground(new java.awt.Color(0, 0, 0));
        lblRGInter.setText("RG:");

        txtRGInter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            txtRGInter.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRGInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRGInterActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblAirlineTick.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblAirlineTick.setForeground(new java.awt.Color(0, 0, 0));
        lblAirlineTick.setText("Airline Tickets:");

        jRBRoundTrip.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jRBRoundTrip.setForeground(new java.awt.Color(0, 0, 0));
        jRBRoundTrip.setText("Round Trip");

        jRBDerpature.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jRBDerpature.setForeground(new java.awt.Color(0, 0, 0));
        jRBDerpature.setText("Departure");
        jRBDerpature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBDerpatureActionPerformed(evt);
            }
        });

        lblBoarding.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblBoarding.setForeground(new java.awt.Color(0, 0, 0));
        lblBoarding.setText("Boarding:");

        txtBoardingInter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDestinyInter.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblDestinyInter.setForeground(new java.awt.Color(0, 0, 0));
        lblDestinyInter.setText("Destiny:");

        txtDestinyInter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDestinyInter1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblDestinyInter1.setForeground(new java.awt.Color(0, 0, 0));
        lblDestinyInter1.setText("Destiny:");

        txtDestinyInter1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCBPassportCheck.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCBPassportCheck.setForeground(new java.awt.Color(0, 0, 0));
        jCBPassportCheck.setText("Passport Checked");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRGInter, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRGInter)
                    .addComponent(txtCPFInter, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCPFInter)
                    .addComponent(txtEmailInter, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNameInter, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAirlineTick)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRBRoundTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRBDerpature))
                    .addComponent(lblBoarding)
                    .addComponent(txtBoardingInter, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDestinyInter)
                    .addComponent(txtDestinyInter, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDestinyInter1)
                    .addComponent(txtDestinyInter1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBPassportCheck))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblID)
                                .addGap(0, 8, Short.MAX_VALUE))
                            .addComponent(txtID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNameInter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailInter, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCPFInter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCPFInter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRGInter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRGInter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(lblAirlineTick)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRBRoundTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRBDerpature))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBoarding)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBoardingInter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDestinyInter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDestinyInter, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDestinyInter1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDestinyInter1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBPassportCheck)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jpButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameInterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameInterActionPerformed

    private void bntUpdateInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntUpdateInterActionPerformed
        // TODO add your handling code here:
        InterPassenger inPas = new InterPassenger();

        if (jCBPassportCheck.isSelected()){
            inPas.setPassport("Sim");
        } else {
            inPas.setPassport("Não");
        }
        inPas.setName(txtNameInter.getText());
        inPas.setEmail(txtEmailInter.getText());
        inPas.setCpf(txtCPFInter.getText());
        inPas.setRg(txtRGInter.getText());
        inPas.setBoarding(txtBoardingInter.getText());
        inPas.setDestiny(txtDestinyInter.getText());

        inPas.setCode(Integer.parseInt(txtID.getText()));

        InterPassengerDAO dao = new InterPassengerDAO();
        dao.passengerUpdate(inPas);

    }//GEN-LAST:event_bntUpdateInterActionPerformed

    private void bntDeleteInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDeleteInterActionPerformed
        // TODO add your handling code here:
        InterPassenger inPas = new InterPassenger();

        inPas.setCode(Integer.parseInt(txtID.getText()));

        InterPassengerDAO dao = new InterPassengerDAO();
        dao.deletePassenger(inPas);
    }//GEN-LAST:event_bntDeleteInterActionPerformed

    private void bntSaveInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSaveInterActionPerformed
        // TODO add your handling code here:
        InterPassenger inPas = new InterPassenger();

        if (jCBPassportCheck.isSelected()){
            inPas.setPassport("Sim");
        } else {
            inPas.setPassport("Não");
        }
        inPas.setName(txtNameInter.getText());
        inPas.setEmail(txtEmailInter.getText());
        inPas.setCpf(txtCPFInter.getText());
        inPas.setRg(txtRGInter.getText());
        inPas.setBoarding(txtBoardingInter.getText());
        inPas.setDestiny(txtDestinyInter.getText());

        InterPassengerDAO dao = new InterPassengerDAO();
        dao.savePassenger(inPas);
    }//GEN-LAST:event_bntSaveInterActionPerformed

    private void txtEmailInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailInterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailInterActionPerformed

    private void txtRGInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRGInterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRGInterActionPerformed

    private void jRBDerpatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBDerpatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBDerpatureActionPerformed

    private void bntMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMainActionPerformed
        // TODO add your handling code here:
        MainScreen Screen = new MainScreen();
        Screen.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_bntMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(International.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(International.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(International.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(International.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new International().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bntDeleteInter;
    private javax.swing.JButton bntMain;
    public javax.swing.JButton bntNewInter;
    public javax.swing.JButton bntSaveInter;
    public javax.swing.JButton bntUpdateInter;
    public javax.swing.JCheckBox jCBPassportCheck;
    public javax.swing.JRadioButton jRBDerpature;
    public javax.swing.JRadioButton jRBRoundTrip;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpButtons;
    private javax.swing.JLabel lblAirlineTick;
    private javax.swing.JLabel lblBoarding;
    private javax.swing.JLabel lblCPFInter;
    private javax.swing.JLabel lblDestinyInter;
    private javax.swing.JLabel lblDestinyInter1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRGInter;
    public javax.swing.JTextField txtBoardingInter;
    public javax.swing.JFormattedTextField txtCPFInter;
    public javax.swing.JTextField txtDestinyInter;
    public javax.swing.JTextField txtDestinyInter1;
    public javax.swing.JTextField txtEmailInter;
    public javax.swing.JTextField txtID;
    public javax.swing.JTextField txtNameInter;
    public javax.swing.JFormattedTextField txtRGInter;
    // End of variables declaration//GEN-END:variables
}
