/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.AetherVoyages.view;

import br.com.AetherVoyages.dao.PassengerDAO;
import br.com.AetherVoyages.model.Passenger;

/**
 *
 * @author wslav
 */
public class National extends javax.swing.JFrame {

    /**
     * Creates new form National
     */
    public National() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bntUpdateNatio = new javax.swing.JButton();
        bntNewNatio = new javax.swing.JButton();
        bntDeleteNatio = new javax.swing.JButton();
        bntSaveNatio = new javax.swing.JButton();
        bntMain = new javax.swing.JButton();
        txtIDNatio = new javax.swing.JTextField();
        lblIDNatio = new javax.swing.JLabel();
        lblNameNatio = new javax.swing.JLabel();
        txtNameNatio = new javax.swing.JTextField();
        lblEmailNatio = new javax.swing.JLabel();
        txtEmailNatio = new javax.swing.JTextField();
        lblCPFNatio = new javax.swing.JLabel();
        txtCPFNatio = new javax.swing.JFormattedTextField();
        lblRGNatio = new javax.swing.JLabel();
        txtRGNatio = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblAirlineTickNatio = new javax.swing.JLabel();
        jRBRoundTripNatio = new javax.swing.JRadioButton();
        jRBDepartureNatio = new javax.swing.JRadioButton();
        lblBoardingNatio = new javax.swing.JLabel();
        txtBoardingNatio = new javax.swing.JTextField();
        lblDestinyNatio = new javax.swing.JLabel();
        txtDestinyNatio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bntUpdateNatio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bntUpdateNatio.setForeground(new java.awt.Color(0, 0, 0));
        bntUpdateNatio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/AetherVoyages/img/businessapplication_edit_male_user_thepencil_theclient_negocio_2321.png"))); // NOI18N
        bntUpdateNatio.setText("Update");
        bntUpdateNatio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntUpdateNatioActionPerformed(evt);
            }
        });

        bntNewNatio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bntNewNatio.setForeground(new java.awt.Color(0, 0, 0));
        bntNewNatio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/AetherVoyages/img/business_application_addmale_useradd_insert_add_user_client_2312 (1).png"))); // NOI18N
        bntNewNatio.setText("New");

        bntDeleteNatio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bntDeleteNatio.setForeground(new java.awt.Color(0, 0, 0));
        bntDeleteNatio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/AetherVoyages/img/delete_delete_deleteusers_delete_male_user_maleclient_2348.png"))); // NOI18N
        bntDeleteNatio.setText("Delete");
        bntDeleteNatio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDeleteNatioActionPerformed(evt);
            }
        });

        bntSaveNatio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bntSaveNatio.setForeground(new java.awt.Color(0, 0, 0));
        bntSaveNatio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/AetherVoyages/img/Save_37110.png"))); // NOI18N
        bntSaveNatio.setText("Save");
        bntSaveNatio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSaveNatioActionPerformed(evt);
            }
        });

        bntMain.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bntMain.setForeground(new java.awt.Color(0, 0, 0));
        bntMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/AetherVoyages/img/Login_37128.png"))); // NOI18N
        bntMain.setText("Main");
        bntMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntUpdateNatio)
                .addGap(18, 18, 18)
                .addComponent(bntNewNatio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntDeleteNatio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntSaveNatio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntMain)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntUpdateNatio)
                    .addComponent(bntNewNatio)
                    .addComponent(bntDeleteNatio)
                    .addComponent(bntSaveNatio)
                    .addComponent(bntMain, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        txtIDNatio.setEditable(false);
        txtIDNatio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIDNatio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtIDNatio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDNatioActionPerformed(evt);
            }
        });

        lblIDNatio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblIDNatio.setForeground(new java.awt.Color(0, 0, 0));
        lblIDNatio.setText("ID:");

        lblNameNatio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblNameNatio.setForeground(new java.awt.Color(0, 0, 0));
        lblNameNatio.setText("Name:");

        txtNameNatio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNameNatio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNameNatio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameNatioActionPerformed(evt);
            }
        });

        lblEmailNatio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblEmailNatio.setForeground(new java.awt.Color(0, 0, 0));
        lblEmailNatio.setText("E-mail:");

        txtEmailNatio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmailNatio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCPFNatio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblCPFNatio.setForeground(new java.awt.Color(0, 0, 0));
        lblCPFNatio.setText("CPF:");

        txtCPFNatio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            txtCPFNatio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblRGNatio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblRGNatio.setForeground(new java.awt.Color(0, 0, 0));
        lblRGNatio.setText("RG:");

        txtRGNatio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            txtRGNatio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblAirlineTickNatio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblAirlineTickNatio.setForeground(new java.awt.Color(0, 0, 0));
        lblAirlineTickNatio.setText("Airline Tickets:");

        jRBRoundTripNatio.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jRBRoundTripNatio.setForeground(new java.awt.Color(0, 0, 0));
        jRBRoundTripNatio.setText("Round Trip");

        jRBDepartureNatio.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jRBDepartureNatio.setForeground(new java.awt.Color(0, 0, 0));
        jRBDepartureNatio.setText("Departure");

        lblBoardingNatio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblBoardingNatio.setForeground(new java.awt.Color(0, 0, 0));
        lblBoardingNatio.setText("Boarding:");

        txtBoardingNatio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBoardingNatio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDestinyNatio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblDestinyNatio.setForeground(new java.awt.Color(0, 0, 0));
        lblDestinyNatio.setText("Destiny:");

        txtDestinyNatio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDestinyNatio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRGNatio, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRGNatio)
                    .addComponent(txtCPFNatio, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCPFNatio)
                    .addComponent(txtEmailNatio, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameNatio)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIDNatio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDNatio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNameNatio, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailNatio))
                .addGap(41, 41, 41)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAirlineTickNatio)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRBRoundTripNatio)
                        .addGap(18, 18, 18)
                        .addComponent(jRBDepartureNatio))
                    .addComponent(lblBoardingNatio)
                    .addComponent(txtBoardingNatio)
                    .addComponent(lblDestinyNatio)
                    .addComponent(txtDestinyNatio))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblIDNatio)
                                    .addComponent(txtIDNatio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNameNatio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNameNatio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEmailNatio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmailNatio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCPFNatio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCPFNatio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRGNatio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRGNatio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(lblAirlineTickNatio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRBRoundTripNatio)
                                    .addComponent(jRBDepartureNatio))
                                .addGap(12, 12, 12)
                                .addComponent(lblBoardingNatio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBoardingNatio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDestinyNatio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDestinyNatio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDNatioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDNatioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDNatioActionPerformed

    private void txtNameNatioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameNatioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameNatioActionPerformed

    private void bntUpdateNatioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntUpdateNatioActionPerformed
        // TODO add your handling code here:
        Passenger pas = new Passenger();

        pas.setName(txtNameNatio.getText());
        pas.setEmail(txtEmailNatio.getText());
        pas.setCpf(txtCPFNatio.getText());
        pas.setRg(txtRGNatio.getText());
        pas.setBoarding(txtBoardingNatio.getText());
        pas.setDestiny(txtDestinyNatio.getText());

        pas.setCode(Integer.parseInt(txtIDNatio.getText()));

        PassengerDAO dao = new PassengerDAO();
        dao.passengerUpdate(pas);
    }//GEN-LAST:event_bntUpdateNatioActionPerformed

    private void bntDeleteNatioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDeleteNatioActionPerformed
        // TODO add your handling code here:
        Passenger pas = new Passenger();

        pas.setCode(Integer.parseInt(txtIDNatio.getText()));

        PassengerDAO dao = new PassengerDAO();
        dao.deletePassenger(pas);
    }//GEN-LAST:event_bntDeleteNatioActionPerformed

    private void bntSaveNatioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSaveNatioActionPerformed
        // TODO add your handling code here:
        Passenger pas = new Passenger();

        pas.setName(txtNameNatio.getText());
        pas.setEmail(txtEmailNatio.getText());
        pas.setCpf(txtCPFNatio.getText());
        pas.setRg(txtRGNatio.getText());
        pas.setBoarding(txtBoardingNatio.getText());
        pas.setDestiny(txtDestinyNatio.getText());

        PassengerDAO dao = new PassengerDAO();
        dao.savePassenger(pas);
    }//GEN-LAST:event_bntSaveNatioActionPerformed

    private void bntMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMainActionPerformed
        // TODO add your handling code here:
        MainScreen Screen = new MainScreen();
        Screen.setVisible(true);
        
    }//GEN-LAST:event_bntMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(National.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(National.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(National.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(National.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new National().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bntDeleteNatio;
    private javax.swing.JButton bntMain;
    public javax.swing.JButton bntNewNatio;
    public javax.swing.JButton bntSaveNatio;
    public javax.swing.JButton bntUpdateNatio;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JRadioButton jRBDepartureNatio;
    public javax.swing.JRadioButton jRBRoundTripNatio;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAirlineTickNatio;
    private javax.swing.JLabel lblBoardingNatio;
    private javax.swing.JLabel lblCPFNatio;
    private javax.swing.JLabel lblDestinyNatio;
    private javax.swing.JLabel lblEmailNatio;
    private javax.swing.JLabel lblIDNatio;
    private javax.swing.JLabel lblNameNatio;
    private javax.swing.JLabel lblRGNatio;
    public javax.swing.JTextField txtBoardingNatio;
    public javax.swing.JFormattedTextField txtCPFNatio;
    public javax.swing.JTextField txtDestinyNatio;
    public javax.swing.JTextField txtEmailNatio;
    private javax.swing.JTextField txtIDNatio;
    public javax.swing.JTextField txtNameNatio;
    public javax.swing.JFormattedTextField txtRGNatio;
    // End of variables declaration//GEN-END:variables
}
